general:
  verbose: true
steps:
  mtaBuild:
    buildTarget: 'CF'
    script: this
      cloudFoundryDeploy:
     deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
        org: 'trial'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
