general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
        org: '13de008f-2f89-4242-a733-fb20ec445b74'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
