general:
  steps:
  mtaBuild:
    buildTarget: 'CF'
       script: this
      cloudFoundry:
        org: 'trial'
        space: 'dev'
        deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
        credentialsId: 'CF-jenkins-credentials-id'
