general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundry:
        org: '4683088dtrial'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
        cloudFoundryDeploy:
  deployTool: 'mtaDeployPlugin'
