steps:
  mtaBuild:
    buildTarget: 'CF'
  deployTool: 'mtaDeployPlugin'
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'c85591detrial'
      space: 'dev'
      credentialsId: 'CF-jenkins-credentials-id'
