general:
  verbose: true
  buildTool: mta
  steps:
    mtaBuild:
      buildTarget: 'CF'
    cloudFoundryDeploy:
      deployTool: 'mtaDeployPlugin'
      deployType: 'standard'
      cloudFoundry:
        org: '4683088dtrial'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
    tmsUpload:
      credentialsId: tms_secret_id
      nodeName: uat
      mtaPath: .
      customDescription: Custom-Transport-Description
      buildTool: mta
  # uploading MTA extension descriptors, optional step
      mtaVersion: 1.0.0
      nodeExtDescriptorMapping:
        PRE-PROD: 'scv_x_preprod.mtaext'
        PROD: 'scv_x_prod.mtaext'
        buildTool: mta

  stages:
    Release:
      tmsUpload: true
      buildTool: mta
