general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    cloudFoundry:
    deployTool: 'mtaDeployPlugin'
        org: 'c85591detrial'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
