steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '4683088dtrial'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      space: 'dev'
      credentialsId: 'CF-jenkins-credentials-id'
