 cloudFoundryDeploy:
    cloudFoundry:
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        org: '13de008f-2f89-4242-a733-fb20ec445b74'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
