general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    cloudFoundryDeploy(
    script: script,
    cloudFoundry: [apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com', org: 'c85591detrial', space: 'dev',
credentialsId: 'CF-jenkins-credentials-id'],
deployTool: 'mtaDeployPlugin'
      )
      
