general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    verbose : true
    cloudFoundry:
        org: 'c85591detrial'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
