general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    script: this
    verbose: true
    cloudFoundryDeploy:
     deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
        org: 'trial'
        space: 'dev'
        credentialsId: 'CF-jenkins-credentials-id'
